#!/bin/bash

#packet loss command

#node1
cat planetlab4.mini.pw.edu.pl/pingdata_rut | gawk '(/packets/){print $6}' >> planetlab4.mini.pw.edu.pl/packetloss
#node2
cat planetlab-2.calpoly-netlab.net/pingdata | gawk '(/packets/){print $6}' >> planetlab-2.calpoly-netlab.net/packetloss
#node3
cat planetlab04.cs.washington.edu/pingdata | gawk '(/packets/){print $6}' >> planetlab04.cs.washington.edu/packetloss
#node4
cat planetlab1.cs.purdue.edu/pingdata | gawk '(/packets/){print $6}' >> planetlab1.cs.purdue.edu/packetloss
#node5
cat planetlab3.cs.uoregon.edu/pingdata | gawk '(/packets/){print $6}' >> planetlab3.cs.uoregon.edu/packetloss
#node6
cat planetlab3.rutgers.edu/pingdata_pl | gawk '(/packets/){print $6}' >> planetlab3.rutgers.edu/packetloss
#node7
cat planetlab5.eecs.umich.edu/pingdata | gawk '(/packets/){print $6}' >> planetlab5.eecs.umich.edu/packetloss
#node8
cat planetlab5.ie.cuhk.edu.hk/pingdata | gawk '(/packets/){print $6}' >> planetlab5.ie.cuhk.edu.hk/packetloss
#node9
cat planetlabone.ccs.neu.edu/pingdata | gawk '(/packets/){print $6}' >> planetlabone.ccs.neu.edu/packetloss
#node10
cat plink.cs.uwaterloo.ca/pingdata | gawk '(/packets/){print $6}' >> plink.cs.uwaterloo.ca/packetloss

#Hop count

#node1
cat planetlab4.mini.pw.edu.pl/traceroute_rut | gawk '(/165.230.49.118) /){print $1}' >> planetlab4.mini.pw.edu.pl/hopcount
#node2
cat planetlab-2.calpoly-netlab.net/traceroute | gawk '(/128.208.4.99) /){print $1}' >> planetlab-2.calpoly-netlab.net/hopcount
#node3
cat planetlab04.cs.washington.edu/traceroute | gawk '(/128.208.4.99) /){print $1}' >> planetlab-2.calpoly-netlab.net/hopcount
#node4
cat planetlab1.cs.purdue.edu/traceroute | gawk '(/128.208.4.99) /){print $1}' >> planetlab1.cs.purdue.edu/hopcount
#node5
cat planetlab3.cs.uoregon.edu/traceroute | gawk '(/128.208.4.99) /){print $1}' >> planetlab3.cs.uoregon.edu/hopcount
#node6
cat planetlab3.rutgers.edu/traceroute_pl | gawk '(/128.208.4.99) /){print $1}' >> planetlab3.rutgers.edu/hopcount
#node7
cat planetlab5.eecs.umich.edu/traceroute | gawk '(/128.208.4.99) /){print $1}' >> planetlab5.eecs.umich.edu/hopcount
#node8
cat planetlab5.ie.cuhk.edu.hk/traceroute | gawk '(/128.208.4.99) /){print $1}' >> planetlab5.ie.cuhk.edu.hk/hopcount
#node9
cat planetlabone.ccs.neu.edu/traceroute | gawk '(/128.208.4.99) /){print $1}' >> planetlabone.ccs.neu.edu/hopcount
#node10
cat plink.cs.uwaterloo.ca/traceroute | gawk '(/128.208.4.99) /){print $1}' >> plink.cs.uwaterloo.ca/hopcount


#RTT time calculation

#node1
awk '
/^PING / {h=$2}
/packet loss/ {pl=$6}
/min\/avg\/max/ {
split($4,a,"/")
printf("%s \n",a[2])
}
' planetlab4.mini.pw.edu.pl/pingdata_rut >> planetlab4.mini.pw.edu.pl/rtt

#node2
awk '
/^PING / {h=$2}
/packet loss/ {pl=$6}
/min\/avg\/max/ {
split($4,a,"/")
printf("%s \n",a[2])
}
' planetlab-2.calpoly-netlab.net/pingdata >> planetlab-2.calpoly-netlab.net/rtt

#node3
awk '
/^PING / {h=$2}
/packet loss/ {pl=$6}
/min\/avg\/max/ {
split($4,a,"/")
printf("%s \n",a[2])
}
' planetlab04.cs.washington.edu/pingdata >> planetlab04.cs.washington.edu/rtt

#node4
awk '
/^PING / {h=$2}
/packet loss/ {pl=$6}
/min\/avg\/max/ {
split($4,a,"/")
printf("%s \n",a[2])
}
' planetlab1.cs.purdue.edu/pingdata >> planetlab1.cs.purdue.edu/rtt

#node5
awk '
/^PING / {h=$2}
/packet loss/ {pl=$6}
/min\/avg\/max/ {
split($4,a,"/")
printf("%s \n",a[2])
}
' planetlab3.cs.uoregon.edu/pingdata >> planetlab3.cs.uoregon.edu/rtt

#node6
awk '
/^PING / {h=$2}
/packet loss/ {pl=$6}
/min\/avg\/max/ {
split($4,a,"/")
printf("%s \n",a[2])
}
' planetlab3.rutgers.edu/pingdata_pl >> planetlab3.rutgers.edu/rtt

#node7
awk '
/^PING / {h=$2}
/packet loss/ {pl=$6}
/min\/avg\/max/ {
split($4,a,"/")
printf("%s \n",a[2])
}
' planetlab5.eecs.umich.edu/pingdata_rut >> planetlab5.eecs.umich.edu/rtt

#node8
awk '
/^PING / {h=$2}
/packet loss/ {pl=$6}
/min\/avg\/max/ {
split($4,a,"/")
printf("%s \n",a[2])
}
' planetlab5.ie.cuhk.edu.hk/pingdata_rut >> planetlab5.ie.cuhk.edu.hk/rtt

#node9
awk '
/^PING / {h=$2}
/packet loss/ {pl=$6}
/min\/avg\/max/ {
split($4,a,"/")
printf("%s \n",a[2])
}
' planetlabone.ccs.neu.edu/pingdata_rut >> planetlabone.ccs.neu.edu/rtt

#node10
awk '
/^PING / {h=$2}
/packet loss/ {pl=$6}
/min\/avg\/max/ {
split($4,a,"/")
printf("%s \n",a[2])
}
' plink.cs.uwaterloo.ca/pingdata_rut >> plink.cs.uwaterloo.ca/rtt